# Generated by Django 4.1.9 on 2023-06-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizes",
                to="quiz.quizcategory",
            ),
            preserve_default=False,
        ),
    ]
