# Generated by Django 4.1.9 on 2023-06-30 07:18

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_alter_quiz_options_alter_quizanswer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")], default="DRAFT", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="quizcategory",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["slug"], name="quiz_quiz_slug_a23648_idx"),
        ),
        migrations.AddIndex(
            model_name="quizcategory",
            index=models.Index(fields=["slug"], name="quiz_quizca_slug_f3c981_idx"),
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(fields=["uuid"], name="quiz_quizqu_uuid_e5bb54_idx"),
        ),
    ]
